kind: pipeline
type: docker
name: default

trigger:
  ref:
  - refs/heads/main
  - refs/heads/**

volumes:
  - name: certs
    temp: {}
  - name: dockersocket
    host:
      path: /var/run/docker.sock

steps:
  - name: fetch-tags
    image:  quay.io/unikiosk/test-base
    commands:
      - git fetch --tags
  - name: lint
    image: quay.io/unikiosk/test-base
    commands:
      - make lint
  - name: test
    image:  quay.io/unikiosk/test-base
    volumes:
    - name: dockersocket
      path: /var/run/docker.sock
    commands:
      - make test
  - name: build
    image: quay.io/unikiosk/test-base
    commands:
      - docker login --username "$${DOCKER_USERNAME}" --password "$${DOCKER_PASSWORD}" quay.io
      - make buildx-image
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    volumes:
    - name: dockersocket
      path: /var/run/docker.sock